theme: jekyll-theme-cayman
title: Groupe de Travail - Stats & Probas
description: Organisé un vendredi sur deux (environ) au LPSM.
footer: 'The template of this webpage and its contents can be found on <a href="https://github.com/Guillaume-Garrigos/gdt-stats-probas">Github</a>.'

plugins:
  - jemoji
